name: Deploy Website to Freehostia

on:
  push:
    branches:
      - main  # Ganti ke 'master' jika branch utama Anda di GitHub adalah master

jobs:
  web-deploy:
    name: Deploy Files via FTP
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Sync files to Freehostia
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: cloud3.googiehost.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Folder default untuk DirectAdmin adalah public_html
        server-dir: /public_html/ 
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**